default: test

######################################################################
# Run all tests

.PHONY: test
test:
	cd test && python test_all.py

######################################################################
# Other targets

clean:
	-rm -rf *.o *.vpi obj_dir test/obj_dir test/logs
