.PHONY: all general toVerilog2 toVHDL toVerilog

all: general toVerilog2 toVHDL toVerilog

general:
	cd general; make -k

toVerilog2:
	cd toVerilog2; make -k

toVHDL:
	cd toVHDL; make -k

toVerilog: 
	cd toVerilog; make -k 
